/** Declaration file generated by dts-gen */

export = pdfh5;

declare class pdfh5 {
    constructor(dom: any, options: any);

    destroy(callback: any): void;

    finalRender(options: any): void;

    goto(num: any): void;

    hide(callback: any): void;

    init(options: any): any;

    off(type: any): void;

    on(type: any, callback: any): void;

    renderCanvas(page: any, viewport: any, pageNum: any, num: any, container: any, options: any): any;

    renderPdf(options: any, obj: any): any;

    renderSvg(page: any, scaledViewport: any, pageNum: any, num: any, container: any, options: any, viewport: any): any;

    reset(callback: any): void;

    resize(): void;

    scrollEnable(flag: any): void;

    show(callback: any): void;

    zoomEnable(flag: any): void;

}

